libcdoc/Io.h, libcdoc/Tar.cpp, libcdoc/cdoc-tool.cpp
* Implemented storing of file name without path when encrypting;
* Implemented saving decrypted files when decrypting;
* Fixed couple of memory leaks.
=> Save decrypted files

.gitignore, CMakeLists.txt, libcdoc/CDoc2Writer.cpp, libcdoc/CMakeLists.txt, libcdoc/Crypto.cpp, libcdoc/PKCS11Backend.cpp, libcdoc/Recipient.cpp, libcdoc/cdoc-tool.cpp
* Implemented encryption by providing a DER file with public key;
* Some white-space changes;
* Added checking if a library is provided if an operation requires it;
Signed-off-by: Firstname Lastname <firstname.lastname@example.com>
=> Encryption with Public-Key file

CMakeLists.txt, libcdoc/CDoc1Writer.cpp, libcdoc/CDocChipher.cpp, libcdoc/CDocChipher.h, libcdoc/CMakeLists.txt, libcdoc/Io.h, libcdoc/RcptInfo.h, libcdoc/ToolConf.h, libcdoc/cdoc-tool.cpp, test/libcdoc_boost.cpp
* Moved command line arguments handling back to cdoc_tool.cpp;
* Updated unit-tests;
* Fixed lambda expression bug in CDoc1Writter that caused warning on compilation.
=> Handle command line arguments in cdoc_tool.cpp

CMakeLists.txt, libcdoc/CDoc2.h, libcdoc/CDocChipher.cpp, libcdoc/CDocChipher.h, libcdoc/CMakeLists.txt, libcdoc/Certificate.cpp, libcdoc/Certificate.h, libcdoc/RcptInfo.h, libcdoc/Recipient.cpp, libcdoc/Recipient.h, libcdoc/ToolConf.h, libcdoc/Utils.cpp, libcdoc/Utils.h, libcdoc/cdoc-tool.cpp, test/libcdoc_boost.cpp
* Implemented Lock's Label auto generation if not provided by user;
* Implemented parsing of auto generated labels;
* Introduced Test Fixtures for unit tests;
* Implemented unit tests for testing parsing of machine generated labels.
=> Label auto generation

CMakeLists.txt, libcdoc/CDoc1Writer.cpp, libcdoc/CDocChipher.cpp, libcdoc/CMakeLists.txt, libcdoc/ConsoleLogger.h, libcdoc/Crypto.cpp, libcdoc/Crypto.h, libcdoc/ILogger.h, libcdoc/LogEngine.cpp, libcdoc/Utils.h, libcdoc/cdoc-tool.cpp
* Added ILogger abstract class as a base class for implementing all possible loggers;
* Introduced log levels;
* Implemented logging to console (ConsoleLogger class);
* Moved Crypto class to new logger and implemented OpenSSL errors logging;
* Moved CDocChipher to new logger;
* Output tool's help only in case of invalid arguments or their values.
=> Logger support

.github/workflows/build.yml, CMakePresets.json, CMakeUserPresets.json, cdoc/CMakeLists.txt, vcpkg.json
=> Add macOS/iOS/iOSSimulator CI builds

CMakeLists.txt
=> Use Project source dir

.github/workflows/build.yml
=> Build arm64 ubuntu packages

cdoc/CDoc.cpp, cdoc/CDoc.h, cdoc/CDoc1Reader.h, cdoc/CDoc1Writer.h, cdoc/CDocChipher.h, cdoc/CDocReader.h, cdoc/CDocWriter.h, cdoc/Certificate.h, cdoc/Configuration.h, cdoc/Crypto.h, cdoc/CryptoBackend.cpp, cdoc/CryptoBackend.h, cdoc/DDocReader.h, cdoc/DDocWriter.h, cdoc/Exports.h, cdoc/ILogger.h, cdoc/Io.cpp, cdoc/Io.h, cdoc/Lock.cpp, cdoc/LogEngine.cpp, cdoc/NetworkBackend.cpp, cdoc/NetworkBackend.h, cdoc/Tar.h, cdoc/ToolConf.h, cdoc/Utils.cpp, cdoc/WinBackend.cpp, cdoc/Wrapper.h, cdoc/XmlReader.h, cdoc/XmlWriter.h, cdoc/ZStream.h
=> ﻿Cleanup header includes

cdoc/CDoc1Reader.cpp, cdoc/CDoc1Writer.cpp, cdoc/CDoc2Reader.cpp, cdoc/CMakeLists.txt, cdoc/Crypto.cpp, cdoc/Crypto.h, cdoc/utils/memory.h
=> Fix memory leaks and add helper memory.h util

cdoc/CDoc2Writer.cpp, cdoc/ConsoleLogger.h, cdoc/CryptoBackend.cpp, cdoc/cdoc-tool.cpp
Fail if symmetric key is not 32 bytes
Output debug and trace to stderr
=> Fail if symmetric key is not 32 bytes

.github/workflows/build.yml, CMakePresets.json, cdoc/CDoc.cpp, cdoc/CDoc.h, cdoc/CDoc2Reader.cpp, cdoc/CDocChipher.cpp, cdoc/CDocReader.h, cdoc/Io.cpp, cdoc/Io.h, libcdoc.i, test/CMakeLists.txt, test/libcdoc_boost.cpp
Fixed various code and buildsystem things to get automated tests working on Windows
=> Fixed test on windows

cdoc/CDoc1Writer.cpp, cdoc/Certificate.cpp, cdoc/Crypto.cpp, cdoc/Crypto.h, cdoc/NetworkBackend.cpp, cdoc/PKCS11Backend.cpp
=> Reuse code and replace some manually handled memory management

cdoc/CDocReader.h, cdoc/CDocWriter.h, cdoc/Configuration.h, cdoc/ConsoleLogger.h, cdoc/CryptoBackend.h, cdoc/Lock.h, cdoc/PKCS11Backend.cpp, cdoc/PKCS11Backend.h, cdoc/Recipient.h, cdoc/WinBackend.h, libcdoc.i
Added Doxygen comments to all public methods/structs/enums
Signed-off-by: Lauris Kaplinski <lauris@kaplinski.com>
=> Finished Doxygen comment

cdoc/CDocCipher.cpp, cdoc/CDocCipher.h, cdoc/CMakeLists.txt, cdoc/cdoc-tool.cpp, test/CMakeLists.txt, test/libcdoc_boost.cpp
=> Rename CDocChipher to CDocCipher, related code changes

cdoc/CDoc1Reader.cpp, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/Utils.h, test/libcdoc_boost.cpp
=> Check input parameters and return error

cdoc/CDoc1Writer.cpp, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/Crypto.cpp, cdoc/CryptoBackend.cpp, cdoc/ILogger.h, cdoc/cdoc-tool.cpp
=> Log keys to TRACE level

README.md, cdoc/CDoc.cpp, cdoc/CDoc1Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/CDocCipher.cpp, cdoc/Certificate.cpp, cdoc/Certificate.h, cdoc/Configuration.h, cdoc/CryptoBackend.h, cdoc/Exports.h, cdoc/Lock.h, cdoc/NetworkBackend.cpp, cdoc/NetworkBackend.h, cdoc/Recipient.cpp, cdoc/Recipient.h, cdoc/ToolConf.h, cdoc/Utils.cpp, cdoc/Utils.h, doc/usage.md, libcdoc.i
=> Add helper methods

cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/CDocCipher.cpp, cdoc/CDocCipher.h, cdoc/Configuration.h, cdoc/NetworkBackend.cpp, cdoc/NetworkBackend.h, cdoc/RcptInfo.h, cdoc/Recipient.cpp, cdoc/Recipient.h, cdoc/Tar.cpp, cdoc/ToolConf.h, cdoc/cdoc-tool.cpp, cdoc/schema/header.fbs, cdoc/schema/recipients.fbs, libcdoc.i, test/libcdoc_boost.cpp
cdoc-tool re-encrypt and keyshare encryption support
=> cdoc-tool re-encrypt and keyshare encryption support

cdoc/PKCS11Backend.h
Some documentation fixes
Signed-off-by: Lauris Kaplinski <lauris.kaplinski@raulwalter.com>
=> Some documentation fixes

.github/workflows/build.yml, cdoc/CDoc.cpp, cdoc/CDoc1Reader.cpp, cdoc/CDoc1Writer.cpp, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/Certificate.cpp, cdoc/Certificate.h, cdoc/Crypto.cpp, cdoc/CryptoBackend.cpp, cdoc/CryptoBackend.h, cdoc/Io.cpp, cdoc/Io.h, cdoc/Lock.cpp, cdoc/NetworkBackend.cpp, cdoc/NetworkBackend.h, cdoc/PKCS11Backend.cpp, cdoc/Recipient.cpp, cdoc/Tar.cpp, cdoc/Tar.h, cdoc/XmlWriter.cpp
=> Fix coverity warnings

README.md, doc/intro.md, doc/usage.md
* Added intro.md with introduction and key features of the library;
* Updated usage.md by adding cdoc-tool description and usage examples;
* Updated README.md by adding configuring and building instructions for different platforms.
PS! Windows part is incomplete!
=> Documentation update

cdoc/CDoc1Writer.cpp, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/Crypto.cpp, cdoc/DDocWriter.cpp, cdoc/DDocWriter.h, cdoc/PKCS11Backend.cpp, cdoc/Utils.cpp, cdoc/Utils.h, cdoc/XmlReader.cpp, cdoc/XmlWriter.cpp, cdoc/XmlWriter.h
=> Fix CodeQL warnings

cdoc/CDoc1Reader.cpp, cdoc/CDoc1Reader.h, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Reader.h, cdoc/CDocCipher.cpp, cdoc/CDocReader.h, doc/usage.md, libcdoc.i
=> Avoid making copy of Lock list

cdoc/NetworkBackend.cpp, cdoc/NetworkBackend.h, libcdoc.i
=> Add proxy support

cdoc/CDoc.h, cdoc/CDoc2Reader.cpp, cdoc/CDoc2Writer.cpp, cdoc/Crypto.cpp, cdoc/Crypto.h, cdoc/NetworkBackend.cpp, cdoc/ToolConf.h, cdoc/Utils.cpp, cdoc/Utils.h
Made NetworkBackend insensitive to terminal '/'
Clear FMK, HHK and cipher ASAP during encryption
=> Better url handling and key clearing

.github/workflows/build.yml, cdoc/CDoc1Reader.cpp, cdoc/CryptoBackend.cpp, cdoc/XmlReader.cpp, cdoc/XmlWriter.cpp, cdoc/XmlWriter.h
=> Fix CDoc1 double free

CMakeLists.txt, cdoc/NetworkBackend.cpp, cdoc/Utils.cpp
Do not put extra '/' to url-s without path
=> Fixed NetworkBackend path building

cdoc/CDoc1Reader.cpp, examples/java/src/main/java/ee/ria/cdoc/CDocTool.java
Signed-off-by: Lauris Kaplinski <lauris.kaplinski@raulwalter.com>
=> Fixed JNI loading and CDoc1::getLockForCert error message

cdoc/CDoc1Writer.cpp, cdoc/DDocWriter.cpp, cdoc/DDocWriter.h, cdoc/XmlWriter.cpp, cdoc/XmlWriter.h
=> CDoc1 XmlWriter error handling
